# Generated by Django 5.2.8 on 2026-04-19 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_restaurant_uids(apps, schema_editor):
    Restaurants = apps.get_model("restaurants", "Restaurants")
    RestaurantBranches = apps.get_model("restaurants", "RestaurantBranches")

    for restaurant in Restaurants.objects.filter(uid__isnull=True).only("id").iterator():
        Restaurants.objects.filter(pk=restaurant.pk).update(uid=uuid.uuid4())

    for branch in RestaurantBranches.objects.filter(uid__isnull=True).only("id").iterator():
        RestaurantBranches.objects.filter(pk=branch.pk).update(uid=uuid.uuid4())


def reverse_populate_restaurant_uids(apps, schema_editor):
    # No destructive reverse data migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranches',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_restaurant_uids,
            reverse_populate_restaurant_uids,
        ),
        migrations.AlterField(
            model_name='restaurantbranches',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurantbranches')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurants')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
