# Generated by Django 5.2.8 on 2025-12-15 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranches',
            name='password',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='password',
        ),
        migrations.AddField(
            model_name='restaurantbranches',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='branch_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='restaurant_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
