# Generated by Django 5.2.8 on 2026-01-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurantbranches_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranches',
            name='banner',
        ),
    ]
