# Generated by Django 5.2.8 on 2026-01-05 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurantbranches_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='admins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'branch_admin'}, related_name='branch_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='admins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'restaurant_admin'}, related_name='restaurant_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
