# Generated by Django 5.2.8 on 2026-01-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurantbranches_admins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranches',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='admins',
        ),
    ]
