# Generated by Django 5.2.8 on 2026-04-19 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('restaurants', '0002_restaurantbranches_uid_restaurants_uid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='food_category_logos/'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='foodmenubranch',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='foodmenubranchcollection',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='restaurants.restaurantbranches'),
        ),
    ]
