# Generated by Django 5.2.8 on 2026-01-17 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_photo', models.ImageField(blank=True, default='default_user.png', null=True, upload_to='media/profile_photos/')),
                ('notification', models.BooleanField(default=False)),
                ('promotional_notification', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('super_admin', 'super_admin'), ('restaurant_admin', 'restaurant_admin'), ('branch_admin', 'branch_admin'), ('user', 'user')], default='super_admin', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('managed_branches', models.ManyToManyField(blank=True, related_name='admins', to='restaurants.restaurantbranches')),
                ('managed_restaurants', models.ManyToManyField(blank=True, related_name='admins', to='restaurants.restaurants')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('name', models.CharField(blank=True, help_text='Manzil nomi (Uy, Ish, ...)', max_length=100, null=True)),
                ('address', models.CharField(help_text="To'liq manzil", max_length=255)),
                ('apartment', models.CharField(blank=True, help_text='Kvartira raqami', max_length=50, null=True)),
                ('entrance', models.CharField(blank=True, help_text='Kirish', max_length=50, null=True)),
                ('floor', models.CharField(blank=True, help_text='Qavat', max_length=50, null=True)),
                ('door_phone', models.CharField(blank=True, help_text='Domofon kodi', max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, help_text="Qo'shimcha ko'rsatmalar", null=True)),
                ('default', models.BooleanField(default=False, help_text='Asosiy manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'users_address',
                'ordering': ['-default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Karta nomi (Mening kartam, Ish kartasi...)', max_length=100, null=True)),
                ('card_number', models.CharField(help_text='Karta raqami (masalan: 8600 1234 5678 9012)', max_length=19, unique=True)),
                ('card_name', models.CharField(default='UzCard', help_text='Karta egasining ismi', max_length=100)),
                ('card_expiry_date', models.CharField(help_text='Amal qilish muddati (MM/YY)', max_length=5)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Telefon raqami', max_length=20, null=True)),
                ('default', models.BooleanField(default=False, help_text='Asosiy karta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'users_card',
                'ordering': ['-default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('device_hardware', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(blank=True, max_length=300, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=300, null=True)),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'users_device',
                'ordering': ['-last_online'],
            },
        ),
    ]
