# Generated by Django 5.2.8 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "super_admin"),
                    ("restaurant_admin", "restaurant_admin"),
                    ("branch_admin", "branch_admin"),
                    ("courier", "courier"),
                    ("user", "user"),
                ],
                default="super_admin",
                max_length=50,
            ),
        ),
    ]
