# Generated by Django 5.2.8 on 2025-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0013_alter_card_card_name_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('restaurant_admin', 'restaurant_admin'), ('branch_admin', 'branch_admin'), ('user', 'user')], default='super_admin', max_length=50),
        ),
    ]
